# Default values for redis-with-sentinel.

#Change storage class and capacity.
storage:
  storageClassName: ""
  redisStorage: "12Gi"
  sentinelStorage: "1Gi"

#Redis and sentinel security pass.
securityContext:
  redisPass: "admin"
  sentinelPass: "admin"

#Redis recource and limits. 
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podSecurityContext: {}
